CREATE TABLE DAY_OF_WEEK (
    ID          SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE SCHEDULE (
    ID          SERIAL PRIMARY KEY,
    DAY_OF_WEEK_ID INT,
    OPEN_AT     TIME,
    CLOSE_AT    TIME,
    CONSTRAINT FK_DAY_OF_WEEK
      FOREIGN KEY(DAY_OF_WEEK_ID) 
	  REFERENCES DAY_OF_WEEK(ID)
);