INSERT INTO DAY_OF_WEEK(ID, DESCRIPTION)
VALUES (1, 'LUNES');

INSERT INTO DAY_OF_WEEK(ID, DESCRIPTION)
VALUES (2, 'MARTES');

INSERT INTO DAY_OF_WEEK(ID, DESCRIPTION)
VALUES (3, 'MIERCOLES');

INSERT INTO DAY_OF_WEEK(ID, DESCRIPTION)
VALUES (4, 'JUEVES');

INSERT INTO DAY_OF_WEEK(ID, DESCRIPTION)
VALUES (5, 'VIERNES');

INSERT INTO DAY_OF_WEEK(ID, DESCRIPTION)
VALUES (6, 'SABADO');

INSERT INTO DAY_OF_WEEK(ID, DESCRIPTION)
VALUES (7, 'DOMINGO');