version: "3.1"

services:
  db:
    image: postgres:16.0
    restart: always
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=go-password-test
      - POSTGRES_USER=go-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

# Use this file to start the container with the postgresql engine
# docker compose -f docker-compose.dev.yml up